sudo: false
language: ruby
cache: bundler
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - rbx
gemfile:
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_4.1.gemfile
  - gemfiles/activerecord_4.0.gemfile
  - gemfiles/activerecord_3.2.gemfile
  - gemfiles/activerecord_3.1.gemfile
  - gemfiles/activerecord_3.0.gemfile
matrix:
  exclude:
    - rvm: 2.1.10
      gemfile: gemfiles/activerecord_5.0.gemfile
    - rvm: rbx
      gemfile: gemfiles/activerecord_5.0.gemfile
  allow_failures:
    - rvm: rbx
  fast_finish: true
addons:
  code_climate:
    repo_token: a90435ed4954dd6e9f3697a20c5bc3754f67d94703f870e8fc7b00f69f5b2d06
